version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/phonebook
  test:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/phonebook
    command: ['npm', 'run', 'test:ci']
  mongodb:
    container_name: mongodb
    image: mongo:4.1
    ports:
      - "27017:27017"